package com.traffic.incidentreporter.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;

@Entity
@Table(name = "incidents")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Incident {

    @Id
    // @GeneratedValue is REMOVED to support custom filling of ID gaps as requested
    private Long id;

    private String type; // ACCIDENT, FIRE, CRASH
    
    @Column(name = "description_text", columnDefinition = "LONGTEXT")
    private String description; // Generated by Gemini

    private String imageUrl; // Path or URL to the snapshot

    private LocalDateTime timestamp;

    private String location; // Could be lat/long or camera ID

    private boolean alertSent; // Status of WebSocket alert
}
